### PR TITLE
add ID for resourcegroup to outputs

### PR DESCRIPTION
**Pull request by salami738**
The generated resource group ID was missing. We need that for creating resource locks per resource group.

### CODE REVIEW

**Comment by dploeger** [comment]
I'm sorry, could you please rebase this again and afterwards run

    docker run -v "$PWD":/terraform ghcr.io/dodevops/terraform-module-tools:latest

Thanks!

**Comment by salami738** [comment]
Hi,

the output from the above command was:

```
~/workspace/terraform-azure-basics$ docker run -v "$PWD":/terraform ghcr.io/dodevops/terraform-module-tools:latest
﹥ Running terraform fmt
﹥ Running tflint
5 issue(s) found:

Warning: terraform "required_version" attribute is required (terraform_required_version)

  on  line 0:
   (source code not available)

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.2.2/docs/rules/terraform_required_version.md

Warning: Missing version constraint for provider "azurerm" in "required_providers" (terraform_required_providers)

  on main.tf line 15:
  15: resource "azurerm_proximity_placement_group" "ppg" {

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.2.2/docs/rules/terraform_required_providers.md

Warning: List items should be accessed using square brackets (terraform_deprecated_index)

  on outputs.tf line 23:
  23:   value       = var.lock ? azurerm_management_lock.resource-group-level.0.id : ""

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.2.2/docs/rules/terraform_deprecated_index.md

Warning: List items should be accessed using square brackets (terraform_deprecated_index)

  on outputs.tf line 23:
  23:   value       = var.lock ? azurerm_management_lock.resource-group-level.0.id : ""

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.2.2/docs/rules/terraform_deprecated_index.md

Warning: List items should be accessed using square brackets (terraform_deprecated_index)

  on outputs.tf line 23:
  23:   value       = var.lock ? azurerm_management_lock.resource-group-level.0.id : ""

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.2.2/docs/rules/terraform_deprecated_index.md
```

This command doesn't do any change to my previous code. I think the code was already properly formatted.

**Comment by dploeger** [comment]
Did you rebase on main before that? Those things are fixed in main.

**Comment by salami738** [comment]
Done, please review.

**Review by dploeger — APPROVED** [review]
Awesome thanks! 🎁

**Pull request merged**
